#TEMPLATE = lib
#CONFIG += staticlib
SOURCES = \
    material-ui/qtmaterialavatar.cpp \
    material-ui/lib/qtmaterialstyle.cpp \
    material-ui/lib/qtmaterialtheme.cpp \
    material-ui/qtmaterialbadge.cpp \
    material-ui/lib/qtmaterialoverlaywidget.cpp \
    material-ui/qtmaterialcheckbox.cpp \
    material-ui/lib/qtmaterialcheckable_internal.cpp \
    material-ui/lib/qtmaterialcheckable.cpp \
    material-ui/lib/qtmaterialripple.cpp \
    material-ui/lib/qtmaterialrippleoverlay.cpp \
    material-ui/qtmaterialfab.cpp \
    material-ui/qtmaterialraisedbutton.cpp \
    material-ui/qtmaterialflatbutton_internal.cpp \
    material-ui/qtmaterialflatbutton.cpp \
    material-ui/lib/qtmaterialstatetransition.cpp \
    material-ui/qtmaterialiconbutton.cpp \
    material-ui/qtmaterialprogress_internal.cpp \
    material-ui/qtmaterialprogress.cpp \
    material-ui/qtmaterialcircularprogress_internal.cpp \
    material-ui/qtmaterialcircularprogress.cpp \
    material-ui/qtmaterialslider_internal.cpp \
    material-ui/qtmaterialslider.cpp \
    material-ui/qtmaterialsnackbar_internal.cpp \
    material-ui/qtmaterialsnackbar.cpp \
    material-ui/qtmaterialradiobutton.cpp \
    material-ui/qtmaterialtoggle_internal.cpp \
    material-ui/qtmaterialtoggle.cpp \
    material-ui/qtmaterialtextfield_internal.cpp \
    material-ui/qtmaterialtextfield.cpp \
    material-ui/qtmaterialtabs_internal.cpp \
    material-ui/qtmaterialtabs.cpp \
    material-ui/qtmaterialscrollbar_internal.cpp \
    material-ui/qtmaterialscrollbar.cpp \
    material-ui/qtmaterialdialog_internal.cpp \
    material-ui/qtmaterialdialog.cpp \
    material-ui/qtmaterialdrawer_internal.cpp \
    material-ui/qtmaterialdrawer.cpp \
    material-ui/qtmaterialappbar.cpp \
    material-ui/qtmaterialautocomplete.cpp \
    material-ui/qtmaterialpaper.cpp \
    material-ui/qtmaterialtable.cpp \
    material-ui/layouts/qtmaterialsnackbarlayout.cpp \
    material-ui/qtmaterialautocomplete_internal.cpp \
    material-ui/qtmaterialmenu.cpp \
    material-ui/qtmaterialmenu_internal.cpp \
    material-ui/qtmateriallist.cpp \
    material-ui/qtmateriallistitem.cpp
HEADERS = \
    material-ui/qtmaterialavatar_p.h \
    material-ui/qtmaterialavatar.h \
    material-ui/lib/qtmaterialstyle_p.h \
    material-ui/lib/qtmaterialstyle.h \
    material-ui/lib/qtmaterialtheme_p.h \
    material-ui/lib/qtmaterialtheme.h \
    material-ui/qtmaterialbadge_p.h \
    material-ui/qtmaterialbadge.h \
    material-ui/lib/qtmaterialoverlaywidget.h \
    material-ui/qtmaterialcheckbox_p.h \
    material-ui/qtmaterialcheckbox.h \
    material-ui/lib/qtmaterialcheckable_internal.h \
    material-ui/lib/qtmaterialcheckable_p.h \
    material-ui/lib/qtmaterialripple.h \
    material-ui/lib/qtmaterialrippleoverlay.h \
    material-ui/lib/qtmaterialcheckable.h \
    material-ui/qtmaterialfab_p.h \
    material-ui/qtmaterialfab.h \
    material-ui/qtmaterialraisedbutton_p.h \
    material-ui/qtmaterialraisedbutton.h \
    material-ui/qtmaterialflatbutton_internal.h \
    material-ui/qtmaterialflatbutton_p.h \
    material-ui/qtmaterialflatbutton.h \
    material-ui/lib/qtmaterialstatetransition.h \
    material-ui/lib/qtmaterialstatetransitionevent.h \
    material-ui/qtmaterialiconbutton_p.h \
    material-ui/qtmaterialiconbutton.h \
    material-ui/qtmaterialprogress_internal.h \
    material-ui/qtmaterialprogress_p.h \
    material-ui/qtmaterialprogress.h \
    material-ui/qtmaterialcircularprogress_internal.h \
    material-ui/qtmaterialcircularprogress_p.h \
    material-ui/qtmaterialcircularprogress.h \
    material-ui/qtmaterialslider_internal.h \
    material-ui/qtmaterialslider_p.h \
    material-ui/qtmaterialslider.h \
    material-ui/qtmaterialsnackbar_internal.h \
    material-ui/qtmaterialsnackbar_p.h \
    material-ui/qtmaterialsnackbar.h \
    material-ui/qtmaterialradiobutton_p.h \
    material-ui/qtmaterialradiobutton.h \
    material-ui/qtmaterialtoggle_internal.h \
    material-ui/qtmaterialtoggle_p.h \
    material-ui/qtmaterialtoggle.h \
    material-ui/qtmaterialtextfield_internal.h \
    material-ui/qtmaterialtextfield_p.h \
    material-ui/qtmaterialtextfield.h \
    material-ui/qtmaterialtabs_internal.h \
    material-ui/qtmaterialtabs_p.h \
    material-ui/qtmaterialtabs.h \
    material-ui/qtmaterialscrollbar_internal.h \
    material-ui/qtmaterialscrollbar_p.h \
    material-ui/qtmaterialscrollbar.h \
    material-ui/qtmaterialdialog_internal.h \
    material-ui/qtmaterialdialog_p.h \
    material-ui/qtmaterialdialog.h \
    material-ui/qtmaterialdrawer_internal.h \
    material-ui/qtmaterialdrawer_p.h \
    material-ui/qtmaterialdrawer.h \
    material-ui/qtmaterialappbar.h \
    material-ui/qtmaterialappbar_p.h \
    material-ui/qtmaterialautocomplete.h \
    material-ui/qtmaterialautocomplete_p.h \
    material-ui/qtmaterialpaper.h \
    material-ui/qtmaterialpaper_p.h \
    material-ui/qtmaterialtable.h \
    material-ui/qtmaterialtable_p.h \
    material-ui/layouts/qtmaterialsnackbarlayout.h \
    material-ui/layouts/qtmaterialsnackbarlayout_p.h \
    material-ui/qtmaterialautocomplete_internal.h \
    material-ui/qtmaterialmenu.h \
    material-ui/qtmaterialmenu_p.h \
    material-ui/qtmaterialmenu_internal.h \
    material-ui/qtmateriallist.h \
    material-ui/qtmateriallist_p.h \
    material-ui/qtmateriallistitem.h \
    material-ui/qtmateriallistitem_p.h
RESOURCES += \
    material-ui/resources.qrc
